import MetaTrader5 as mt5

# --- 1. CONFIGURATION (V6.4) ---
SYMBOL = "XAUUSD"       # CHECK BROKER SYMBOL
TIMEFRAME = mt5.TIMEFRAME_M30
RISK_PERCENT = 0.02       # 2% Risk
MAGIC_NUMBER = 888064     # V6.4 Magic Number
MAX_SPREAD_NORMAL = 50    
MAX_SPREAD_HIGH_CONF = 100 

# --- STRATEGY SETTINGS ---
ADX_THRESHOLD = 20.0      # MINIMUM Trend Strength (Blocks Chop)

# --- RISK LIMITS ---
MAX_SURVIVABLE_LOSS_USD = 25.00 # Iron Clad Cap

# --- AI & STRATEGY SETTINGS ---
CONFIDENCE_ENTRY = 0.55    
CONFIDENCE_REVERSAL = 0.60 
HIGH_CONFIDENCE_LVL = 0.65 
EMA_SECONDARY = 50        
TRAINING_SIZE = 15000      

# --- ORACLE HORIZON SETTINGS ---
PREDICTION_HORIZON = 4      
MIN_HORIZON_RETURN = 0.0015